### ISSUE TITLE
Make tag available for other steps to use

### ISSUE THREAD

**Issue by dardanos** [mr-smithers-excellent/docker-build-push#11]
I would like to use a slack action to notify my team about the new versions and for that, I need access to the image tag. Is there a way to get access to it?

```yml      
     - id: image_tag
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: myimage/myimagename
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'myimage/myimagename:${{ steps.image_tag.outputs.tag }}'
          icon_url: ':shipit:'
          username: 'CI Bot'
          channel: '#build'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
```
