### ISSUE TITLE
Github action Error: Dockerfile does not exist in location Dockerfile

### ISSUE THREAD

**Issue by salamisodikiolawale** [mr-smithers-excellent/docker-build-push#114]
i need to build and push my docker image on dockerHub but i'm getting error on path Dockerfile.
i had learn other ([Build Docker image using GitHub Actions: No such file or directory](https://stackoverflow.com/questions/69204872/build-docker-image-using-github-actions-no-such-file-or-directory)) but i don't understand how can resolve this error.

```
service:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/service

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: dockercountname/aos_movie_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

```

```
My Local directory: i have many subForlder for each service and each service contains his Dockerfile.

microservice_cicd(forlder)
   microservices(forlder)
     service1(forlder)
       package.json
       Dockerfile
       ...
     service2(forlder)
       package.json
       Dockerfile
       ...

```
This an dockerfile for one service

```
FROM node:latest
RUN mkdir -p /src/app
WORKDIR /src/app
COPY package.json /src/app/package.json
RUN npm install
COPY . /src/app
EXPOSE 3003
CMD [ "npm", "start" ]

```

**Comment by mr-smithers-excellent** [comment]
Hi @salamisodikiolawale - are you attempting to build a Docker image for each microservice here? If so, you may need to utilize a matrix or repeat the action for each image you want to build. There is a `dockerfile` and `directory` input that you can utilize for this action as well. This action defaults to a `Dockerfile` in the root project directory unless otherwise specified. Hope this helps.

**Comment by salamisodikiolawale** [comment]
@mr-smithers-excellent, Yes I repeated the action for each image of my microservices but I have the same problem.

```

name: CI-CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

 
  AuthService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/AuthService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: ./microservices/AuthService
          image: sodiki/aos_movie_auth_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: build container
      #   run: docker-compose up -d --build
      
  CrudMovieService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/CrudMovieService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sodiki/aos_movie_crud_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: build container
      #   run: docker-compose up -d --build

  EmailService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/EmailService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sodiki/aos_movie_email_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: build container
      #   run: docker-compose up -d --build

  ReviewService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/ReviewService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sodiki/aos_movie_review_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: build container
      #   run: docker-compose up -d --build

  SearchService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/SearchService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sodiki/aos_movie_search_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: build container
      #   run: docker-compose up -d --build


```

**Comment by mr-smithers-excellent** [comment]
Try adding the `directory` input and set it to the same directory you're setting in `working-directory`

**Comment by salamisodikiolawale** [comment]
I had try directory with AuthService but it same error

```

 AuthService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/AuthService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: ./microservices/AuthService
          image: sodiki/aos_movie_auth_service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

```

**Comment by mr-smithers-excellent** [comment]
Hmmm ok. Perhaps remove `directory` and replace `dockerfile` with:

`dockerfile: microservices/AuthService/Dockerfile`

**Comment by salamisodikiolawale** [comment]
I have other error
```
Step 3/8 : WORKDIR /src/app
 ---> Running in e34f309b6113
Removing intermediate container e34f309b6113
 ---> a53[76](https://github.com/salamisodikiolawale/microservice_cicd/actions/runs/3364791088/jobs/5579550710#step:6:77)8[77](https://github.com/salamisodikiolawale/microservice_cicd/actions/runs/3364791088/jobs/5579550710#step:6:78)e81e
Step 4/8 : COPY package.json /src/app/package.json
COPY failed: file not found in build context or excluded by .dockerignore: stat package.json: file does not exist
Error: Command failed: docker build -f microservices/AuthService/Dockerfile -t docker.io/***/aos_movie_auth_service:latest .
```
```
AuthService:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./microservices/AuthService

      strategy:
        matrix:
          node-version: [16.x]

      steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: BUILDING APP
        run: npm run build --if-present
      #- name: TESTINT APP
      #- run: npm test
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          # directory: /microservices/AuthService
          image: sodiki/aos_movie_auth_service      
          tags: latest
          registry: docker.io
          dockerfile: microservices/AuthService/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
```
