### ISSUE TITLE
 Build The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

### ISSUE THREAD

**Issue by wufengzlw** [mr-smithers-excellent/docker-build-push#116]
Hi,

I'm with the `mr-smithers-excellent/docker-build-push@v5.8`, but still get this warning info from Github.

Did I do anything wrong about the plugin or I still need to wait for the new release?

Thank you

**Comment by mr-smithers-excellent** [comment]
Hi @wufengzlw - can you share your workflow YAML file and the full warning message?

**Comment by wufengzlw** [comment]
@mr-smithers-excellent this is the workflow config:
```
      - name: Docker build and push
        if: steps.image_tag_ready.outcome == 'failure'
        uses: mr-smithers-excellent/docker-build-push@v5.8
        with:
          image: xxxxx-service
          tags: PR-${{ env.PR_NUM }}-${{ env.SHA }}
          registry: xxxxxxxxxxxx.dkr.ecr.us-east-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCKER_USERNAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCKER_PASSWORD }}
```

and here's the warning message:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
