### ISSUE TITLE
Feature request: Change path of build command

### ISSUE THREAD

**Issue by eevers-avisi** [mr-smithers-excellent/docker-build-push#14]
Is it possible to add an option for changing the PATH used in the Docker build command?

As far I can see it is now only possible to achieve something like this:
docker build -f otherPath/Dockerfile -t image:latest .

What I would like to achieve is this:
docker build -f  otherPath/Dockerfile -t image:latest otherPath

**Comment by eevers-avisi** [comment]
I just saw your reaction on the following PR: https://github.com/mr-smithers-excellent/docker-build-push/pull/8

You said that by setting the working directory you should also achieve this. I did also try to do that before creating this issue. Unfortunately this didn't work. 
![image](https://user-images.githubusercontent.com/62014922/79566800-7180f700-80b3-11ea-9e67-a0797652f2e8.png)

**Comment by mr-smithers-excellent** [comment]
Hi @eevers-avisi - thanks for the feedback.  Upon further research, it looks like you can't use `working-directory` in conjunction with `uses`, only with `run`.  So I'll need to make some changes to get this working.  Would something like this fit your use case?

```yaml
    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: 'owner/image-name'
        tag: 'latest'
        registry: 'docker.io'
        dockerfile: '../Dockerfile' # assuming Dockerfile is at root
        directory: 'dir-name' # if running the build outside project root
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

**Comment by eevers-avisi** [comment]
@mr-smithers-excellent Yes, your example would fit my use case

**Comment by mr-smithers-excellent** [comment]
@eevers-avisi - I've been able to get this working on a branch with a new optional `directory` input. Can you give the below example a try and let me know if it works for your purposes? Note that if a standard `Dockerfile` already exists in the working directory, you won't have to specify it. 

```yaml
- uses: mr-smithers-excellent/docker-build-push@add-build-dir
  with:
    image: 'mrsmithers/hello-world'
    tag: 'latest'
    registry: 'docker.io'
    dockerfile: 'working-dir/Dockerfile.dir'
    directory: 'working-dir'
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
```
