### ISSUE TITLE
Second push fails with ` requested access to the resource is denied`

### ISSUE THREAD

**Issue by adamgins** [mr-smithers-excellent/docker-build-push#18]
Thanks fo this package, nice to find one that works with Windows, the others seem to be linux bound.

Issue: when the first build & push happens all is OK, on subsequent builds it fails with:

> Successfully built 7ac415707073
> Successfully tagged <docker image>:dev-9aea4e2
> Pushing Docker image docker.io/ <docker image>:dev-9aea4e2
> The push refers to repository [docker.io/ <docker image>]
> 93a37fc3c4af: Preparing
> c046cedd46c1: Preparing
> 65963877bc32: Preparing
> d03deee11d2e: Preparing
> f686442af91b: Preparing
> 4601355fed1f: Preparing
> 065c56dd8815: Preparing
> a8862db1c285: Preparing
> 3492c6ad7ce2: Preparing
> 4601355fed1f: Waiting
> 065c56dd8815: Waiting
> a8862db1c285: Waiting
> 3492c6ad7ce2: Waiting
> denied: requested access to the resource is denied
> ##[error]Command failed: docker push docker.io/<docker image>:dev-9aea4e2

The workflow is:

```
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
        name: Check out code
    # - uses: actions/checkout@v2
    # - name: Build image from archive
    #   run: docker build <docker build command here... all works fine>
    # - name: Run build-tools build command
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image:<docker image name>
          registry: docker.io
          dockerfile: bundle/Dockerfile
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: <pass some build args all works fine>
  

```

Any help appreciated.

**Comment by mr-smithers-excellent** [comment]
Hi @adamgins - thanks for the feedback here.  Happy to look into this deeper.  Can you provide some details about what your `Dockerfile` looks like or even just the base image so I can reproduce?

**Comment by mr-smithers-excellent** [comment]
Using a simple "hello world" `Dockerfile` I'm not able to replicate this yet:

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN dism.exe /online /enable-feature /all /featurename:iis-webserver /NoRestart

RUN echo "Hello World - Dockerfile" > c:\inetpub\wwwroot\index.html

CMD [ "cmd" ]
```

According to t[his StackOverflow issue](https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker), your issue may be related to the `docker login` operation.

**Comment by adamgins** [comment]
Thanks @mr-smithers-excellent 
I added you to a private repo we run the docker file in the `bundle` directory
Weird that is succeeds with the push the first time to a new docker image and then fails the second time.

**Comment by adamgins** [comment]
@mr-smithers-excellent FYI I did find this long issue https://github.com/docker/hub-feedback/issues/1222

**Comment by mr-smithers-excellent** [comment]
@adamgins - this is helpful. Looking into this more today.

**Comment by mr-smithers-excellent** [comment]
@adamgins - think I found your issue.

**Successful Build Image**
`buzzybuzz/buzzy-main-windows-nano1809:latest`

**Failed Build Image**
`buzzybuzz/buzzy-main-windows:nano1809`

I'm guessing the name of the Docker repo should be `buzzy-main-windows-nano1809`?  Does the repo `buzzybuzz/buzzy-main-windows` exist?

**Comment by adamgins** [comment]
@mr-smithers-excellent thanks. I think that issue was just an example where we changed the image name to a new name `buzzybuzz/buzzy-main-windows-nano1809:latest` and it worked the first time. Both those images existed on docker.io

The weird thing is I got it to work on `buzzybuzz/buzzy-main-windows` by deleting the repo and then re-running, it worked both first and second time. 

The only other things I changed, was I added the `latest` as the `tag` directive:


```
build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
        name: Check out code
    # - uses: actions/checkout@v2
    # - name: Build image from archive
    #   run: docker build --build-arg s3key=${{ secrets.AWS_ID }} --build-arg s3scret=${{ secrets.AWS_SECRET }} --build-arg s3path=s3://<path to s3bucket>/<file>.tar.gz -t buzzybuzz:buzz-main-windows -f bundle/Dockerfile .
    # - name: Run build-tools build command
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: buzzybuzz/buzzy-main-windows
          tag: latest
          registry: docker.io
          dockerfile: bundle/Dockerfile
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: s3key=${{ secrets.AWS_ID }}, s3scret=${{ secrets.AWS_SECRET }}, s3path=s3:/<path to docker bundle>/<file>.tar.gz
```

So I'd say it's working, I still don't know what made it work. The critical thing was deleting the current image.
