### ISSUE TITLE
Ability to push multiple tags

### ISSUE THREAD

**Issue by belon** [mr-smithers-excellent/docker-build-push#22]
## New feature
Would be great to support multiple tags.

### Use case
When release new version we always push two tags:
- ${{ GITHUB.SHA }}
- latest

**Comment by belon** [comment]
I forked you repository and added this feature. Here it is https://github.com/belon/docker-build-push. Commits:
- https://github.com/belon/docker-build-push/commit/697bcf5e2e2af562cf78c23ede4d9554c4443251
- https://github.com/belon/docker-build-push/commit/153acf878752b0df2492c269559e016f1de0b875

I released version `v4.0` with support for multiple tags. The only difference is in configuration use `tags` instead of `tag`. For example:
```
steps:
  - uses: actions/checkout@v1.0
    name: Check out code

  - uses: belon/docker-build-push@v4.0
    name: Build & push Docker image
    with:
      image: repo/image
      tags: v1, latest
      registry: registry-url.io
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
```
