### ISSUE TITLE
Conditionally Setting `addLatest` does not work for truthy values

### ISSUE THREAD

**Issue by CodeVachon** [mr-smithers-excellent/docker-build-push#228]
When using an expression for the `addLatest` input, a trueful value is ignored.

```yml
name: Build

on:
  release:
    types: [published]

jobs:
  Build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v6.3
        name: Build & Push App Docker Image
        with:
          image: app
          registry: ghcr.io
          dockerfile: Dockerfile
          addLatest: ${{ !contains(github.ref_name, 'RC') }}
```

## Expected

With the above workflow:

- If `github.ref_name` is `0.0.0-RC1` the `latest` tag **SHOULD NOT** be added
- If `github.ref_name` is `0.0.0` the `latest` tag **SHOULD** be added 

## Actual

With the above workflow:

- ✅ When `github.ref_name` is `0.0.0-RC1` the `latest` tag **IS NOT** added
- ❌ When `github.ref_name` is `0.0.0` the `latest` tag **IS NOT** added
