### ISSUE TITLE
Does windows platform build work?

### ISSUE THREAD

**Issue by Antonytm** [mr-smithers-excellent/docker-build-push#347]
Workflow:
```
name: Publish antonytm/mcp-sitecore-windows to Docker Hub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: antonytm/mcp-sitecore-windows
          tags: 0.19.11, latest
          registry: docker.io
          dockerfile: ./docker/windows/Dockerfile
          platform: windows/amd64
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
```

Dockerfile:
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]

RUN Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing "https://nodejs.org/dist/v22.16.0/node-v22.16.0-win-x64.zip"; Expand-Archive nodejs.zip -DestinationPath C:\; Rename-Item "C:\\node-v22.16.0-win-x64" c:\nodejs

FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR C:/nodejs
COPY --from=installer C:/nodejs/ .
RUN SETX PATH C:\nodejs
RUN npm config set registry https://registry.npmjs.org/

WORKDIR c:/app

# Install dependencies without prepare scripts
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts

# Build application
COPY src ./src
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

# Default start
CMD ["node","c:/app/dist/index.js"]

# Expose port 3001
EXPOSE 3001
```

Error:
```
ERROR: failed to solve: process "powershell -Command $ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue'; Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing \"[https://nodejs.org/dist/v22.16.0/node-v22.16.0-win-x64.zip\](https://nodejs.org/dist/v22.16.0/node-v22.16.0-win-x64.zip/)"; Expand-Archive nodejs.zip -DestinationPath C:\\; Rename-Item \"C:\\\\node-v22.16.0-win-x64\" c:\\nodejs" did not complete successfully: exit code: 1
```

I tried switching to `cmd`, I tried to set the path variable before the build. Nothing helped.
What did I do wrong?
Does it work with Windows images?
