### ISSUE TITLE
Can't use variable in tag

### ISSUE THREAD

**Issue by tomtom94** [mr-smithers-excellent/docker-build-push#36]
Hello I wanna use a variable in `tag`

Something like this

```
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: myimage
          tag: latest-$VERSION
          registry: rg.nl-ams.scw.cloud/myapp
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        env:
          VERSION: ${{ secrets.VERSION }}
```

It doesn't work why ?
