### ISSUE TITLE
Feature request: add option to add "latest" tag to autogenerated tags

### ISSUE THREAD

**Issue by Strange-Account** [mr-smithers-excellent/docker-build-push#49]
Hi,

I really like the auto generation of tags based on ref. But it would be nice if there was an option to also add a "latest" tag.

eg:
```
uses: mr-smithers-excellent/docker-build-push@v5
with:
  image: docker-hub-repo/image-name
  registry: docker.io
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
  addLatest: true
```

Trigger | Commit SHA | Docker Tag
-- | -- | --
/refs/tags/v1.0 | N/A | v1.0,latest
/refs/heads/dev | 1234567 | dev-1234567,latest
/refs/heads/master | 1234567 | master-1234567,latest
/refs/heads/SOME-feature | 1234567 | some-feature-1234567,latest
