### ISSUE TITLE
Requested access to the resource is denied

### ISSUE THREAD

**Issue by nihil-pro** [mr-smithers-excellent/docker-build-push#74]
Hi
I try to push an image to my private dockerhub calls "nihilpro/repo" but get a error: 
Requested access to the resource is denied
```
`# Build and push docker image
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: nihilpro/repo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}`
```

But if i try to login from my machine with this credentials everything is ok.
