### ISSUE TITLE
Support github packages docker registry

### ISSUE THREAD

**Issue by advait** [mr-smithers-excellent/docker-build-push#9]
It would be great if this action could support [Github Packages docker registry](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages).

It seems Github Actions provides a `GITHUB_TOKEN` secret that has write access to the packages docker registry. It's unclear how this integrates with `docker login`, etc. Given that this is a github action, it would be great to provide support for github's own registry out of the box.

**Comment by mr-smithers-excellent** [comment]
Hi @advait - thank you for the feature request. Completely agree and would be happy to add support. I will do a POC in the next day or so. If there’s anything else special about your use case, please let me know in the meantime.

**Comment by advait** [comment]
Thanks @mr-smithers-excellent! The docs are very sparse on this one. Here's what worked for me:

```
docker login docker.pkg.github.com --username [namespace] --password "${{secrets.GITHUB_TOKEN}}"
docker push docker.pkg.github.com/[namespace]/[package]/[image-name]:[image-tag]
```

The namespace is typically your github username, the package is the github project/package name. The image-name and image-tag are arbitrary.

**Comment by mr-smithers-excellent** [comment]
Hi @advait, I have a branch with GitHub Docker Registry support added. Could you give this a try and let me know how it goes?

* It is assumed you'll be pushing the image to a repo inside your GitHub organization, unless you set `githubOrg`
* Provider the image name in `github-repo-name/image-name` format  
* Provide either the `github.actor` or an alternate username for Docker login
* Pass the default GitHub Actions token or custom secret with [proper push permissions](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token)

```yaml
uses: mr-smithers-excellent/docker-build-push@github-registry
with:
  image: github-repo/image-name
  registry: docker.pkg.github.com
  githubOrg: override-org # optional
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }} 
```
